import { Inter } from 'next/font/google'
import './globals.css'
import { Header } from '@/components/header/header'
// import { Sidebar } from '@/components/Sidebar/sidebar'
// import { ConnectModal } from '@/components/Modal/modal'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  //   title: 'Create Next App',
  //   description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} lg:bg-[url(/assets/images/bg-dsk.png)] sm:bg-[url(/assets/images/bg-mob.png)] bg-cover bg-center text-white w-screen`}>
        {/* <Sidebar /> */}
        <Header />
        {children}
      </body>
    </html>
  )
}
